### ISSUE TITLE
Resumes

### ISSUE THREAD

**Issue by SactoDi** [18F/tts-buy-ckan-multitenant#10]
Question/Comment 5

Diane Hussey, Sr. Proposal Manager

Section 3.7.2 Key Personnel and Section 7.2, Factor 2: Staffing Plan  

Are there specific requirements for fonts, margins, and/or number of pages per resume?

**Comment by JenniferCalik** [comment]
While the Government has not set any formatting requirements or page maximums, Quoters are urged to focus the content of their Key Personnel resumes on succinctly demonstrating the content listed under Section 7.2, Factor 2, while keeping in mind how the Government will evaluate the Staffing Plan factor as described in Section 8.3, Factor 2.
