### ISSUE TITLE
Pages for each section

### ISSUE THREAD

**Issue by eKuber** [18F/tts-buy-ckan-multitenant#11]
## Name and affiliation
Ajay Srivastava Managing Director

## Section of RFQ documents
Quotes & Evaluation

## Question/Comment
Could the government please advise the number of Pages for each section of the Technical Factors 
1) Technical Approach, 2) Staffing Plan  and 3) Similar Experience.

**Comment by JenniferCalik** [comment]
The text response for Factors 1 through 3 are each limited to 12,000 characters.
