### ISSUE TITLE
"Add Files" Option 

### ISSUE THREAD

**Issue by CAHiltonREI** [18F/tts-buy-ckan-multitenant#12]
# Question/Comment

## Section of RFQ documents
RFQ Response Form

## Question/Comment
There is an “Add Files” option on the RFQ response form for the question “Technical Factors Support Files: Upload visual supports for the previous three answers”: 
Is the government expectation that only graphic files are uploaded here to support Factor 1, Factor 2, and Factor 3?       
Are we allowed to upload any word documents here to support the technical approach for Factor 1, Factor 2 and Factor 3 areas of the RFQ?

**Comment by JenniferCalik** [comment]
This upload file has been limited to a single PDF type files and should only include visual supports to the text provided in the text fields provided for Evaluation Factors 1 through 3.  These visual supports may including identifying text (e.g. Exhibit 1, Table 1, Diagram 1, etc.) as well as identifying titles.  This file should not include supplementary text that could not be included within the character limit of the text fields provided for each Factor, therefore circumventing the specified character limits.
