### ISSUE TITLE
Base Period

### ISSUE THREAD

**Issue by CAHiltonREI** [18F/tts-buy-ckan-multitenant#13]
# Question/Comment

## Name and affiliation
Carol Ann Hilton

## Section of RFQ documents
Section 2.1 – Base Period    

## Question/Comment
Is the government also seeking the awarded contractor to move the Inventory.data.gov CKAN instance to this multi-tenant CKAN platform during this base period?

**Comment by JenniferCalik** [comment]
This is not anticipated to happen during the base period.
