### ISSUE TITLE
Section 2.1 – Optional Task 2 

### ISSUE THREAD

**Issue by CAHiltonREI** [18F/tts-buy-ckan-multitenant#14]
# Question/Comment

## Name and affiliation
Carol Ann Hilton, Proposal Manager

## Section of RFQ documents
Section 2.1 – Optional Task 2 

## Question/Comment
In addition to catalog.data.gov, how many additional such CKAN instances with harvesting, geospatial metadata source capabilities does the government expect to migrate to this multi-tenant platform?

**Comment by JenniferCalik** [comment]
None.
