### ISSUE TITLE
Section 2.1 – Option Period    

### ISSUE THREAD

**Issue by CAHiltonREI** [18F/tts-buy-ckan-multitenant#15]
# Question/Comment

## Name and affiliation
Carol Ann Hilton, Proposal Manager

## Section of RFQ documents
Section 2.1 – Option Period  

## Question/Comment
How many participating government  agencies will be hosted in this multi-tenant CKAN platform, assuming  each agency has one CKAN site?  
      1-10, 11-25, 26-50?

**Comment by JenniferCalik** [comment]
At this time the Government does not have an estimate for the total number of agencies to be onboarded to the resulting multi-tenant CKAN platform.  This number will depend largely on the ability of the platform to meet our agency partners’ needs and the value the migration will bring to those agencies.  We anticipate fewer than 10 agencies to be onboarded during the base period and do not currently have an estimate for the option periods.
