### ISSUE TITLE
Request for Extension

### ISSUE THREAD

**Issue by SactoDi** [18F/tts-buy-ckan-multitenant#16]
Question/Comment 6

Diane Hussey, Sr. Proposal Manager

General

With the answers to questions being released on Friday, August 24, 2018, and the possibility that these answers may affect our approach and staffing plan, we respectfully request an extension to the due date so the RFQ response is not due one business day after the release of Q&A.

**Comment by JenniferCalik** [comment]
Based on the quantity and nature of the questions received as well as the Government’s responses to these questions, we do not believe an extension of the solicitation closing is warranted at this time.  All Quoters are encouraged to provide their best possible quotation within the time permitted.
