### ISSUE TITLE
Breakdown of Personnel

### ISSUE THREAD

**Issue by SactoDi** [18F/tts-buy-ckan-multitenant#17]
Question/Comment 7

Diane Hussey, Sr. Proposal Manager

Section 7.2, Factor 2: Staffing

In the second bullet, the first sentence states "A breakdown of the number of personnel by skill levels/labor categories..." and the last sentence states "The breakdown should be consistent with the information submitted on the RFQ Pricing Form..." Does this mean that the breakdown of the number of personnel only needs to include the Key Personnel/personnel we show on the RFQ Pricing Form?

**Comment by JenniferCalik** [comment]
Both the breakdown and the RFQ Pricing form should consistently reflect the total combination of personnel, including Key Personnel and others, needed to satisfy the objectives and requirements of this solicitation.  This information will be utilized both during the evaluation of each quotation as well as serve as the basis for tracking contractor work and processing payments after award.
