### ISSUE TITLE
QASP and Pricing Solicitation Documents point to Google Docs

### ISSUE THREAD

**Issue by jqnatividad** [18F/tts-buy-ckan-multitenant#2]
# Question/Comment
"Attached" solicitation documents - QASP and Pricing form point to Google Docs requiring permission, not the published files on the repo.

## Name and affiliation
Joel Natividad, OpenGov

## Section of RFQ documents
[Preamble](https://github.com/18F/tts-buy-ckan-multitenant/blob/master/solicitation_documents/RFQ.md#preamble) and [Section 2.2.2](https://github.com/18F/tts-buy-ckan-multitenant/blob/master/solicitation_documents/RFQ.md#222-inspection)

## Question/Comment
Can you confirm that the Google Docs are equivalent to the published solicitation documents?

**Comment by jqnatividad** [comment]
The [RFQ technical response form](https://docs.google.com/forms/d/1gr9gHzRJZ2LH6UrRzT4g40npWRi-I3ZYsLi5fv_h5RE) also refers to the Google Doc version of the Pricing Form, requiring permission.

**Comment by JenniferCalik** [comment]
Thank you for these comments.  Links have been updated to GitHub links.
