### ISSUE TITLE
Clarification of Multitenant CKAN

### ISSUE THREAD

**Issue by davidcallner** [18F/tts-buy-ckan-multitenant#3]
# Question/Comment

## Name and affiliation
David Callner, Innovation Director

## Section of RFQ documents
Section 2.1 Tasks

## Question/Comment
Would the government allow for an innovative multi-tenant CKAN solution that already exists that we can migrate to? If yes then would the government allow an ODC CLIN to be added to the price form to account for licence costs which will drastically reduce labor and time of migration.

**Comment by JenniferCalik** [comment]
The Government is not interested in incurring recurring licensing costs, however the Government is open to considering an option of this nature if it can be proposed within the parameters of our established PWS and specified contract/pricing structure.
