### ISSUE TITLE
Security Clearance

### ISSUE THREAD

**Issue by SactoDi** [18F/tts-buy-ckan-multitenant#4]
Question/Comment 1

Diane Hussey, Senior Proposal Manager

Sections 5.2 and 5.4  

18F Source Code Policy (cited in Section 5.2) has general language around security and Section 5.4 states "The Contractor shall ensure that appropriate administrative, ... to ensure the security and confidentiality.... There is no other mention of security or security clearances in the RFQ.  Is there a specific security clearance or clearances required for this contract?

**Comment by JenniferCalik** [comment]
As described in Section 2.1 of the RFQ, the contractor will only be responsible for delivering deployable code to the Government, as such, there is no additional security or security clearance requirements anticipated to be applicable to the resulting contract during the Base Period, however, please see Section 5.3 of the solicitation regarding Non-Disclosure Agreement requirements. If contractor personnel require access to GSA IT systems as a result of the Government exercising any of the Option Periods or Optional Tasks, those contractor personnel will be required to receive a successful determination from the security clearance process for a National Agency Check with written Inquiries (NACI).  The following additional language will be added to the solicitation via Amendment 02:

“5.7 Security Clearance and GSA Access Card
In accordance with Homeland Security Presidential Directive 12 (HSPD-12) and GSA regulations, contractor employees who required access to GSA facilities and IT systems must receive, at the minimum, a successful determination from the security clearance process for a National Agency Check with written Inquiries (NACI) to receive prior to issuance of a GSA Access Card (Access Card). Successful results from the FBI National Criminal History Check (i.e., fingerprint check) portion must be received before an Access Card can be issued. If contractor personnel require access to GSA IT systems as a result of the Government exercising any of the Option Periods or Optional Tasks, those contractor personnel will be required to comply with these requirements. 
 
The Access Card serves as the identity badge and uses smart card technology to provide reliable and secure identity verification. Contractors are required to use their Access Card along with a Personal Identification Number (PIN), to log into GSA networks.
 
The Contractor shall return all badges to the government on the same day that an individual employee is terminated, and/or upon termination or completion of the task order. The Contractor shall notify the Government immediately of any lost or stolen badges. The Government assumes financial responsibility for any fees connected to the clearance process for contractor employees and the issuance and/or maintenance fees for the Access Card.”
