### ISSUE TITLE
Budget

### ISSUE THREAD

**Issue by SactoDi** [18F/tts-buy-ckan-multitenant#6]
Question/Comment 2

Diane Hussey, Senior Proposal Manager

General

What is the budget for this contract?

**Comment by JenniferCalik** [comment]
The Government believes we’ve provided sufficient information on the requirements within the RFQ and the anticipated level of effort between the RFQ and responses to the questions contained in this document for vendors to provide competitive quotations without revealing our Government Cost Estimate.
