### ISSUE TITLE
Format/Page Limitations

### ISSUE THREAD

**Issue by SactoDi** [18F/tts-buy-ckan-multitenant#7]
Question/Comment 3

Diane Hussey, Sr Proposal Manager

Section 7.1, Technical Submittal 

The RFQ Response Form has areas provided for our written response to Factors 1, 2, and 3. Is there a character and/or word limit to our answers, and is there a font requirement? If there is a character/word limit, can we upload our answers to these Factors in the Technical Factors Support files area?

**Comment by JenniferCalik** [comment]
The text response for Factors 1 through 3 are each limited to 12,000 characters.  There are no font requirements for these text responses.  Please see the Government’s response to the Question titled, “Add Files” Option, for additional information regarding the Technical Factors Support Files field of the form.
