### ISSUE TITLE
Build vs Buy vs BuildWith

### ISSUE THREAD

**Issue by jqnatividad** [18F/tts-buy-ckan-multitenant#9]
# Question/Comment

## Name and affiliation
Joel Natividad, OpenGov

## Section of RFQ documents
Pricing Form

## Question/Comment

The current RFQ only specifies GSA Schedule Labor Category items as per the Pricing Form.  Is there any scope to leverage an existing CKAN-as-a-Service Product for the multi-tenant platform? 

Doing so has several advantages:

 *   **Lower Risk.** Existing CKAN-as-a-Service providers have heavily invested in creating their Product and have solved a lot of the multi-tenancy issues that only come with experience running a commercial service (e.g. High Availability; Proactive Monitoring; Analytics; API management; Integrations with ETL tools; dedicated staff (engineers, devops, trainers, support, QA, etc.); [supporting development to improve bulk upload](https://ckan.org/2017/11/20/express-loader-for-ckan-datastore/); Helpdesk; Knowledgebase; SLA; Training; [arranging vendor-agnostic conferences](https://discuss.okfn.org/t/ckanconus-may-29-2018-oakland-ca/6515), etc.)

 *   **Lower Total Cost of Ownership.** GSA directly benefits from economies of scale by leveraging an existing product.

 *   **Economies of Scope.** GSA directly benefits from various use cases for which the product has been adapted by the CKAN-as-a-Service provider (e.g. Data Dictionary built for a City, generalized and contributed back to CKAN core) 

 *   **Continuous Innovation.** GSA directly benefits from continuous innovation on the CKAN-as-a-Service product.  The resulting platform will not be frozen at version 2.8, ([especially with CKAN v3.0, which includes foundational changes to CKAN](https://github.com/ckan/ckan/wiki/Migration-from-Pylons-to-Flask)) and will be able to leverage other innovations on both the CKAN and the providers' roadmap.

 *   **Supports the CKAN Ecosystem.** GSA ensures a healthy ecosystem by supporting commercial CKAN providers.

All this while preserving the following benefits:

  *   **No lock-in.** The Product is architected to not lock-in GSA and its multi-tenant customers.  There is a migration option available to GSA and its multi-tenant customers. 

 *   **Open Source contributions.** [Existing CKAN-as-a-Service providers have been the most active contributors to the CKAN project](https://docs.google.com/presentation/d/1mToPI8nvi7mls3gYzHd18bsCahiAfjajuAHK1ScwOUE/edit#slide=id.g37e92937c7_0_0).  Leveraging an existing Product ensures these contributions continue and even accelerated by GSA, in a manner consistent with [Section 5.2 - Data Rights and Ownership of Deliverables.](https://github.com/18F/tts-buy-ckan-multitenant/blob/master/solicitation_documents/RFQ.md#52-data-rights-and-ownership-of-deliverables)

**Build vs Buy vs BuildWith.** The existing product has been architected so it can be readily extended to suit GSA's specific requirements.  "Building With" the services and platform partners on this platform product allows GSA to reap the benefits of buying a COTS solution with the flexibility of creating a bespoke solution.

**Comment by greggersh** [comment]
Would like to offer a +1 to the above question/suggestion. We would like the opportunity to propose a product-based solution, supplemented by services, that we feel will better meet the needs of GSA, and provide a more cost-effective solution. The RFP as currently written precludes this type of approach, which precludes our ability to propose an effective solution to the government.

In conjunction with the question above, we'd like to request that the government extend the deadline of the proposal to allow us time to formulate a new product-based solution and pricing model.

Thank you!

**Comment by greggersh** [comment]
To follow up, an option would be to modify the pricing template to allow for Other Direct Costs, and let the vendor specify items to be included as part of the solution.

**Comment by jqnatividad** [comment]
For clarity, note that we propose to "leverage" the Product. The resulting platform will be still hosted on GSA's AWS infrastructure.

**Comment by JenniferCalik** [comment]
The Government is open to considering an option of this nature if it can be proposed within the parameters of our established PWS and specified contract/pricing structure
